version: '3.8'

name: pokedex
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  client-service:
    container_name: client-service
    image: pokedex-client-service
    build:
      context: client-service
      dockerfile: ./Dockerfile.dev
    expose:
      - '3000'
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/
    env_file:
      - ./client-service/.env
    volumes:
      - ./client-service/src/:/usr/src/app/src/
      - ./shared/:/usr/src/app/node_modules/shared
    depends_on:
      - pokemon-service

  pokemon-service:
    container_name: pokemon-service
    image: pokedex-pokemon-service
    build:
      context: pokemon-service
      dockerfile: ./Dockerfile.dev
    expose:
      - '8080'
    environment:
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PATH=/api/pokemon-service
    env_file:
      - ./pokemon-service/.env
    volumes:
      - ./pokemon-service/src/:/usr/src/app/src/
      - ./shared/:/usr/src/app/node_modules/shared
    depends_on:
      - nginx-proxy
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./${DATA_PATH:-data}/mongod:/data/db
