FROM node:20.7.0-alpine3.18
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
ENV CI=true
ENV WDS_SOCKET_PORT=0
EXPOSE 3000
CMD [ "npm", "start" , "--ignore-watch" , "\"src/**/*\"" ]
